; hooks for go-mode specific bindings
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-3") (kbd "uint32")))
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-6") (kbd "uint64"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-8") (kbd "uint8"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-1") (kbd "uint16"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-s") (kbd "string"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-b") (kbd "bool"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-c") (kbd "chan"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-<") (kbd "<-chan"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C->") (kbd "chan<-"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
;; (add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
(add-hook 'go-mode-hook (define-key evil-insert-state-map (kbd "C-p") (kbd "map"))) 
